/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Apple-file-promises.h
 #	source generated by 4D Plugin Wizard
 #	Project : Apple file promises
 #	author : miyako
 #	2021/04/11
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_APPLE_FILE_PROMISES_H
#define PLUGIN_APPLE_FILE_PROMISES_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_LONGINT.h"

#if VERSIONMAC
#import <objc/runtime.h>
#import <AppKit/AppKit.h>
#include "Mail.h"
#include "Photos.h"
#include "Outlook.h"
#endif

#define CALLBACK_IN_NEW_PROCESS 0
#define CALLBACK_SLEEP_TIME 59

#include <mutex>

#pragma mark -

/*
 
 not preemptive because of
 
 - PA_NewProcess
 
 */

void ACCEPT_FILE_PROMISES(PA_PluginParameters params);

#endif /* PLUGIN_APPLE_FILE_PROMISES_H */

void listener_start(void);
void listener_end(void);

void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

#define USE_PROMISE_FOR_OUTLOOK 0
#define USE_PROMISE_FOR_PHOTO 0

#define kpbERMessagePasteboardType (NSString *)@"dyn.ah62d4rv4gu8ynywrqz31g2phqzkgc65yqzvg82pwqvnhw6df"
#define kpbOlxMessagePasteboardType (NSString *)@"dyn.ah62d4rv4gu800x5qtbg0n65xqfx0nydbsr4gn2xtqf3gkzd3sbwu"
#define kpbWMOutlookInternalFilePromisePboardType (NSString *)@"dyn.ah62d4rv4gu8zsxntsz4g255trre067dfsm1gc5cgrf0gnydwr700w65fnbvg82pwqvnhw6df"
/*
#ifndef errAEEventWouldRequireUserConsent
enum {
    errAEEventWouldRequireUserConsent     =     -1744
};
#endif
*/
#if VERSIONMAC

@interface AppleFilePromiseListener : NSObject
{
    FSEventStreamRef stream;
}

- (void)setURL:(NSURL *)url;

@end

@interface

Swizzle_XMacNSView_saisierec_Class : NSObject <NSDraggingDestination>
{
    
}

- (void)askPhotosToExport:(NSURL *)url;
- (void)askOutlookToExport:(NSURL *)url;
- (void)askMailToExport:(NSURL *)url;

@end
#endif
