/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Apple file promises
 #	author : miyako
 #	2018/05/14
 #
 # --------------------------------------------------------------------------------*/

#if VERSIONMAC
#import <objc/runtime.h>
#import <AppKit/AppKit.h>
#include "Mail.h"
#include "Photos.h"
#include "Outlook.h"
#endif
#define CALLBACK_IN_NEW_PROCESS 0
#define CALLBACK_SLEEP_TIME 59
#include <mutex>

/*
 
 not preemptive because of
 
 - PA_NewProcess
 
 */

// --- Apple file promises
void ACCEPT_FILE_PROMISES(sLONG_PTR *pResult, PackagePtr pParams);

void listener_start(void);
void listener_end(void);

void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

#define PROCESS_OUTLOOK_BY_SCRIPTING 0
#define USE_FS_EVENT 0

#if VERSIONMAC

@interface AppleFilePromiseListener : NSObject
{
	FSEventStreamRef stream;
}

- (void)setURL:(NSURL *)url;

@end

@interface

Swizzle_XMacNSView_saisierec_Class : NSObject <NSDraggingDestination>
{
	
}

- (void)askPhotosToExport:(NSURL *)url;
- (void)askOutlookToExport:(NSURL *)url;
- (void)askMailToExport:(NSURL *)url;

@end
#endif
